### ISSUE TITLE
ERROR socket hang up

### ISSUE THREAD

**Issue by ghost** [nodester/nodester#200] opened 2011-09-03 16:15 UTC
Hello - nodester username: ajldevelopment appname: ajlstatic

When create a new app I get this:

AJ-Leas-iMac:Sites ajldevelopment$ nodester app init ajlstatic
nodester info initializing git repo for ajlstatic into folder ajlstatic
nodester info cloning the repo git clone git@nodester.com:/node/git/ajldevelopment/3566-0a26967a1613f50769e76670f76ca3c9.git ajlstatic
nodester info clone complete
nodester info Writing app data to config in ajlstatic/.nodester.appconfig
nodester info writing app files
nodester info processing the initial commit
nodester info attemping to start the new app.
nodester ERROR socket hang up

I would appreciate any help. Thanks...
Adam

**Comment by eabait** [comment] 2011-09-05 04:16
Hey,

I'm getting the same error message after restarting my app:

nodester app restart deploytonodester
nodester info Attemping to restart app: deploytonodester
nodester ERROR socket hang up

Thanks.
Esteban

**Comment by yocontra** [comment] 2011-09-06 19:52
We've implemented a large number of changes to the server. Let me know if you are still having the same issues and we can iron them out now

**Comment by eabait** [comment] 2011-09-07 03:44
Hi,

still having the same problem. The application works locally, however I'm not sure if the socket.io configuration is working on the nodester's servers. So, I would like to know if the problem is yours or mine...

Cheers.
Esteban,

**Comment by yocontra** [comment] 2011-09-07 18:52
It's an issue with our API/CLI, everything seems to be fine on your end

**Comment by eabait** [comment] 2011-09-08 13:19
ok, thanks!

**Comment by funkytek** [comment] 2011-09-14 13:15
try again with updated cli? ($ npm install -g nodester-cli)

**Comment by eabait** [comment] 2011-09-14 22:32
Yeah, now it throws the following error:

nodester info Attemping to restart app: deploytonodester

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Cannot read property 'statusCode' of undefined
    at Request.callback (/home/esteban/local/node/lib/node_modules/nodester-cli/node_modules/nodester-api/nodester.js:57:47)
    at Request.<anonymous> (/home/esteban/local/node/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:154:67)
    at Request.emit (events.js:64:17)
    at ClientRequest.<anonymous> (/home/esteban/local/node/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:151:13)
    at ClientRequest.emit (events.js:64:17)
    at Socket.<anonymous> (http.js:1290:31)
    at Socket.emit (events.js:64:17)
    at Array.<anonymous> (net.js:837:12)
    at EventEmitter._tickCallback (node.js:126:26)

**Comment by yocontra** [comment] 2011-09-14 23:48
Oops sorry about that. Just pushed an updated API so you shouldn't get that error anymore.

**Comment by eabait** [comment] 2011-09-22 22:16
I'm getting this now:

nodester info Attemping to restart app: deploytonodester
nodester info { response: '{"status":"false","port":11708,"gitrepo":"git@nodester.com:/node/git/eabait/3555-12db67b1f6c52adde909255edf6b7ab0.git","start":"server.js","running":"failed-to-restart","pid":"failed-to-setup_unionfs_chroot"}',
  errorCode: null }
nodester ERROR false

Again, dont know if the error is the app not being correctly configured to run on the platform or a platform issue per se.

**Comment by ghost** [comment] 2011-09-23 20:04
I am no longer getting any errors

**Comment by yocontra** [comment] 2011-09-24 07:07
I tweaked some things on the server. Glad to see things are working for you AJ

**Comment by yocontra** [comment] 2011-11-01 04:36
Closing issue, seems to be resolved.

**Comment by yocontra** [comment] 2011-11-01 04:37
If anyone is still having issues make sure you update to the latest API/CLI

**Comment by mattSleeman** [comment] 2011-11-03 20:50
Hi, I am having the same issue

node.js:207
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Cannot read property 'statusCode' of undefined
    at /usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/lib/nodester.js:168:16
    at Request.callback (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/lib/nodester.js:3:63)
    at Request.<anonymous> (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:154:67)
    at Request.emit (events.js:67:17)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:151:13)
    at ClientRequest.emit (events.js:67:17)
    at Socket.<anonymous> (http2.js:1089:11)
    at Socket.emit (events.js:67:17)
    at Array.<anonymous> (net_uv.js:497:16)
    at EventEmitter._tickCallback (node.js:199:26)

I tried $ npm install -g nodester-cli and got

npm ERR! Error: getHostByName ECONNREFUSED
npm ERR!     at errnoException (dns_uv.js:31:11)
npm ERR!     at Object.onanswer (dns_uv.js:141:16)
npm ERR! Report this _entire_ log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Linux 2.6.38-8-generic
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "nodester-cli"
npm ERR! cwd /home/matt/node/app
npm ERR! node -v v0.5.8-pre
npm ERR! npm -v 1.0.30
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/matt/node/app/npm-debug.log
npm not ok

Thanks

**Comment by dmh2000** [comment] 2011-11-06 01:05
node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Cannot read property 'statusCode' of undefined
    at /home/dmh2000/local/node/lib/node_modules/nodester-cli/node_modules/nodester-api/lib/nodester.js:168:16
    at Request.callback (/home/dmh2000/local/node/lib/node_modules/nodester-cli/node_modules/nodester-api/lib/nodester.js:3:63)
    at Request.<anonymous> (/home/dmh2000/local/node/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:154:67)
    at Request.emit (events.js:64:17)
    at ClientRequest.<anonymous> (/home/dmh2000/local/node/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:151:13)
    at ClientRequest.emit (events.js:64:17)
    at Socket.<anonymous> (http.js:1290:31)
    at Socket.emit (events.js:64:17)
    at Array.<anonymous> (net.js:831:12)
    at EventEmitter._tickCallback (node.js:126:26)

**Comment by yocontra** [comment] 2011-11-06 10:29
Updated the API. Do a `npm install nodester-cli -g` really quick and it should spit out proper logs now

**Comment by mattSleeman** [comment] 2011-11-06 13:20
This is working for me now, Thanks!

**Comment by yocontra** [comment] 2011-11-06 15:55
Closing it then. Glad to be off assistance!

**Closed as completed by yocontra** 2011-11-06 15:55 UTC
