### ISSUE TITLE
Nodester app "2d" is hanging

### ISSUE THREAD

**Issue by richardanaya** [nodester/nodester#73] opened 2011-03-10 23:30 UTC
I made a series of git pushes, and my application seems unable to stop.  Reset appears to succeed but with no change to the state of the running app, further git pushes do not help, logs give no indication of something wrong.

**Comment by richardanaya** [comment] 2011-03-10 23:31
One important note is that my app is using socket.io

**Comment by davglass** [comment] 2011-03-10 23:48
I just manually restarted it on the server.

**Comment by davglass** [comment] 2011-03-22 14:30
Closed as duplicate of the other "Web Socket" proxy issue..

**Closed as completed by davglass** 2011-03-22 14:30 UTC
