### ISSUE TITLE
"nodester app logs' busted

### ISSUE THREAD

**Issue by akavlie** [nodester/nodester#228] opened 2011-11-08 06:49 UTC
I get this when running it:

```
$ nodester app logs web-irc
nodester info { response: 'Cannot GET /applogsweb-irc',
  errorCode: 404 }
```

**Comment by yocontra** [comment] 2011-11-08 18:56
Ah a missing / in the API. I'll push a fix up right now! Will update when it's public

**Comment by akavlie** [comment] 2011-11-12 04:56
This also affects `nodester npm list`.

Think you can get a fix out soon? Haven't seen anything yet.

**Comment by yocontra** [comment] 2011-11-14 02:11
The CLI and API will have new version out tomorrow. Will update this once public, lots of bug fixes on the way. @akavlie it looks like the npm list is a different issue on it's own but I've fixed it as well.

**Comment by yocontra** [comment] 2011-11-18 21:01
@akavlie - I'm having issues reproducing this. Are you sure you're running the latest version of the API/CLI?

**Comment by yocontra** [comment] 2011-11-18 21:24
NPM list has been fixed as of API 0.1.18

**Comment by akavlie** [comment] 2011-11-18 21:56
I'm running nodester-cli version 0.2.34. `npm update nodester-cli` doesn't give me anything newer than that.

**Comment by yocontra** [comment] 2011-11-18 21:58
Run `npm install nodester-cli -g` for the dependencies to update

**Comment by akavlie** [comment] 2011-11-18 21:59
I'm a little confused as well... are you having trouble reproducing the problem with `nodester npm list`, `nodester app logs`, or both?

Also, was the new version of the CLI get delayed?

**Comment by akavlie** [comment] 2011-11-18 22:02
Cool, after running `npm install` as you suggested both commands work.

Strange... I thought `npm update` was supposed to, well, update? Does it not touch dependencies without another flag?

**Comment by yocontra** [comment] 2011-11-18 22:07
It doesn't update the dependencies (strange). Closing this now as it seems to be solved. Let me know if you have any other issues!

**Closed as completed by yocontra** 2011-11-18 22:07 UTC
Labels: Contra
