### ISSUE TITLE
Init Error

### ISSUE THREAD

**Issue by muellersfranz** [nodester/nodester#101] opened 2011-04-06 13:53 UTC
I'm still getting the same error message when I try to init an app:

nodester app init chili
nodester info initializing git repo for chili into folder chili
nodester info cloning the repo git clone ec2-user@nodester.com:/node/hosted_apps/franz/1147-ab9a1fe919c7f5663775a08cde29c80e.git chili
nodester info clone complete
nodester info writing app data to config

fs.js:221
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor 'chili/.nodester.appconfig'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:512:15)
    at Object.writeApp (/usr/local/lib/node/.npm/nodester-cli/0.2.12/package/lib/config.js:54:8)
    at /usr/local/lib/node/.npm/nodester-cli/0.2.12/package/lib/app.js:230:37
    at ChildProcess.exithandler (child_process.js:106:7)
    at ChildProcess.emit (events.js:67:17)
    at ChildProcess.onexit (child_process.js:192:12)

thx

**Comment by triptych** [comment] 2011-04-07 17:22
I'm seeing the same thing
https://skitch.com/andrewwooldridge/r263a/1-bash

**Comment by triptych** [comment] 2011-04-07 18:14
dav suggested that perhaps becuase my ssh key included a password that that was preventing the script from running properly, however I created a new ssh key and bound that to my acct - but it did not have any effect, however if you are reading this, you may try this yourself to see

**Comment by chrismatthieu** [comment] 2011-04-08 17:50
It looks like this issue is being caused by having an RSA key passphrase.  

Triptych was able to resolve this problem as follows:

triptych: I basically blew away my old .ssh key and created a new one without a password
[10:30am] triptych: uninstalled nodester-cli
[10:30am] triptych: then rebooted
[10:30am] triptych: resetup my gitub acct
[10:30am] triptych: then created a fresh user in the cli

You may also be able to add your passphrase to your keychain using the following technique: http://www-uxsup.csx.cam.ac.uk/~aia21/osx/leopard-ssh.html#Passphrase

We will continue to look for a better solution...

**Comment by triptych** [comment] 2011-04-08 18:12
I initially tried that keychain technique from that ac.uk site but it didn't seem to work for me, but your mileage may vary.

**Comment by chrismatthieu** [comment] 2011-04-29 22:44
johnpaul: giving nodester a try, getting the dreaded Bad file descriptor 'jpa5n/.nodester.appconfig'
[1:17pm] johnpaul: looked up some of the tickets -- no passphrase on my key...
[1:18pm] johnpaul: nodester app clone fails as well
[1:22pm] johnpaul: email address was in public key
[1:22pm] johnpaul: @ sign I believe
[1:22pm] johnpaul: bleah
[1:23pm] johnpaul: problem solved

**Comment by thientruong** [comment] 2011-05-10 16:27
fs.js:221
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor 'letrong/.nodester.appconfig'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:483:15)
    at Object.writeApp (/usr/local/lib/node_modules/nodester-cli/lib/config.js:54:8)
    at /usr/local/lib/node_modules/nodester-cli/lib/app.js:230:37
    at ChildProcess.exithandler (child_process.js:106:7)
    at ChildProcess.emit (events.js:67:17)
    at ChildProcess.onexit (child_process.js:192:12)
[root@www2160uc ~]#

can you tell me steps by all commands to resolve it :(???

**Comment by McWatt** [comment] 2011-05-22 07:03
Has this issue been resolved? I'm getting the same error.

**Comment by chrismatthieu** [comment] 2011-05-22 17:02
No, you need to use an RSA key without a passphrase for now.

**Comment by thientruong** [comment] 2011-05-23 17:58
how, please?

**Comment by McWatt** [comment] 2011-05-23 21:41
Chris,
I should have given you more info. This is what I did based on info further up in this thread:
1. uninstalled nodester-cli
2. followed this github help article and left the passphrase blank:
   http://help.github.com/linux-set-up-git/
3. rebooted
4. added the new key to my github account
5. re-installed nodester-cli
6. followed the steps in your how-to video to add a hello world nodejs app.
7. got the same errors: 

fs.js:221
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor 'erikphipps/.nodester.appconfig'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:522:15)
    at Object.writeApp (/usr/local/lib/node/.npm/nodester-cli/0.2.13/package/lib/config.js:54:8)
    at /usr/local/lib/node/.npm/nodester-cli/0.2.13/package/lib/app.js:230:37
    at ChildProcess.exithandler (child_process.js:106:7)
    at ChildProcess.emit (events.js:67:17)
    at ChildProcess.onexit (child_process.js:192:12)

Any ideas? I pulled these steps from my memory so if they look good, I'll try it again later tonight. Thanks!

**Comment by McWatt** [comment] 2011-06-01 20:31
I figured what I was doing wrong. I needed to update my nodester account with the new key. See this blog post for the details:

http://nodester.tumblr.com/post/4472243958/passwords-and-passphrases-tips

**Comment by DanBUK** [comment] 2011-06-27 11:35
Therefore McWatt is this issue resolved?

If you do have an ssh key with a pass phrase you will need to use an ssh-agent to allow you to not have to present the passphrase each time.

**Comment by Deebster** [comment] 2011-08-13 12:53
I am also getting this issue.

I've tried
1) using my original (passworded) id_rsa with ssh-agent (passwordless ssh worked)
2) a new, no-password id_rsa
3) a new, no-password id_dsa

My last run:
deebster@bernie:~/code$ rm ~/.ssh/id_*
deebster@bernie:~/code$ ssh-keygen -t dsa -C "no at sign here" -N ""
Generating public/private dsa key pair.
Enter file in which to save the key (/home/deebster/.ssh/id_dsa): 
Your identification has been saved in /home/deebster/.ssh/id_dsa.
Your public key has been saved in /home/deebster/.ssh/id_dsa.pub.
The key fingerprint is:
32:31:9e:eb:3c:00:65:aa:ae:f7:43:a8:86:2c:e2:aa no at sign here
The key's randomart image is:
+--[ DSA 1024]----+
|                 |
|    o            |
|   +  o          |
|  o  . +         |
| . o  = S        |
|. . o  +         |
|+. . ..          |
|=+. .o.          |
|Eo ...o.         |
+-----------------+
deebster@bernie:~/code$ nodester user setup deebster myAlphanumericOnlyPass
nodester info verifying credentials
nodester info user verified..
nodester info writing user data to config
deebster@bernie:~/code$ nodester user setkey ~/.ssh/id_dsa
nodester info sending sshkey: /home/deebster/.ssh/id_dsa
nodester info ssh key successfully sent
deebster@bernie:~/code$ nodester app create hellodeeb8
nodester info creating app: hellodeeb8 server.js
nodester info successfully created app hellodeeb8 to will run on port 11317 from server.js
nodester info run nodester app init hellodeeb8 to setup this app.
deebster@bernie:~/code$ nodester app init hellodeeb8
nodester info initializing git repo for hellodeeb8 into folder hellodeeb8
nodester info cloning the repo git clone git@nodester.com:/node/git/deebster/3164-958589d6f9b59a622394c71721cf4539.git hellodeeb8
nodester info clone complete
nodester info writing app data to config

fs.js:221
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor 'hellodeeb8/.nodester.appconfig'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:483:15)
    at Object.writeApp (/usr/local/lib/node_modules/nodester-cli/lib/config.js:54:8)
    at /usr/local/lib/node_modules/nodester-cli/lib/app.js:283:37
    at ChildProcess.exithandler (child_process.js:106:7)
    at ChildProcess.emit (events.js:67:17)
    at ChildProcess.onexit (child_process.js:192:12)

**Comment by yocontra** [comment] 2011-08-13 19:28
Hmm... doing some research showed a few different things that could possibly cause this.

Bit of a shot in the dark but can you run `ulimit -a` and paste back the output?

**Comment by Deebster** [comment] 2011-08-13 19:39
deebster@bernie:/files$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 20
file size               (blocks, -f) unlimited
pending signals                 (-i) 16382
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
deebster@bernie:/files$ node -v && npm -v
v0.4.11-pre
1.0.24

Cheers

**Comment by yocontra** [comment] 2011-08-13 20:21
Are you making sure you adhere to the specifications in http://nodester.tumblr.com/post/4472243958/passwords-and-passphrases-tips ?

EDIT: I'm an idiot and didn't read your previous post, nvm. I'm stumped with this one, I'll keep looking at the code

**Comment by Deebster** [comment] 2011-08-23 12:36
I've updated my version of node to v0.4.12-pre but still the same error.

**Comment by Deebster** [comment] 2011-08-24 09:53
Previously it seemed to be the `git clone` stage which was failing with nodester (although fine with github) but it suddenly started working.

I now seem to be getting slightly further:

**deebster@bernie:~/code$ nodester app create hellodeebf**
nodester info creating app: hellodeebf server.js
nodester info successfully created app hellodeebf to will run on port 11501 from server.js
nodester info run nodester app init hellodeebf to setup this app.
deebster@bernie:~/code$ nodester app init !$
**nodester app init hellodeebf**
nodester info initializing git repo for hellodeebf into folder hellodeebf
nodester info cloning the repo git clone git@nodester.com:/node/git/deebster/3348-546fd962c5885302a07f04010a9e61a6.git hellodeebf
nodester info clone complete
nodester info Writing app data to config in hellodeebf/.nodester.appconfig
nodester info writing app files
nodester info processing the initial commit
nodester info attemping to start the new app.
nodester ERROR false
deebster@bernie:~/code$ nodester app logs !$
**nodester app logs hellodeebf**
nodester ERROR HTTP Error 500
**deebster@bernie:~/code$ node -v && npm -v && nodester -v**
v0.4.12-pre
1.0.26
0.2.20
**deebster@bernie:~/code$ cat hellodeebf/server.js**
var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\nApp (hellodeebf) is running..');
}).listen(11501);

**Comment by yocontra** [comment] 2011-08-25 09:19
What version of the CLI are you running? I fixed the EBADF error in the latest revision. Your new issue seems to be unrelated, you might want to try opening a new issue for it.

Chris opened a similar issue and closed it later saying it was fixed. You might want to try again

**Closed as completed by yocontra** 2011-08-25 09:19 UTC
Labels: Awaiting Close
